# Generated by Django 5.1.6 on 2025-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='title',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
